fix/update to chron 030
blockchaintp/chronicle-examples pull request #16
Opened 2022-11-10 01:27 UTC by scealiontach

- fix(make): update makefile to support arm64/amd64 images
- docs: updates for 0.3.0 conventions

2022-11-10 10:19 UTC, duncanjw requested changes
I will have a go at fixing these issues

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
> +  itemManufactured(externalId"rotorbladefab-20221014-001",attributes:{batchIdAttribute:"20221014-001"}) {
foo now defineFoo
Missing colon after externalId

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
> +  item(externalId"rotorblade-20221014-0001",attributes:{partIdAttribute:"20221014-0001"}) {
foo now defineFoo
Missing colon after externalId

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
> +  itemCertified(externalId"rotorbladecert-20221014-0001") {
foo now defineFoo
Missing colon after externalId

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
> +  certificate(externalId"rotorbladecert-20221014-0001",attributes:{certIdAttribute:"20221014-0001"}) {
foo now defineFoo
Missing colon after externalId

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
>      correlationId,
As above
correlationId now txId
also the format of context returned is different

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
>      correlationId
As above
correlationId now txId
also the format of context returned is different

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
>      correlationId,
As above
correlationId now txId
also the format of context returned is different

2022-11-10 10:19 UTC, duncanjw commented on domains/manufacturing/guide.md
>      correlationId
As above
correlationId now txId
also the format of context returned is different

2022-11-10 11:01 UTC, duncanjw commented on domains/manufacturing/guide.md
>      correlationId
This also means updating the subscription in README.md

2022-11-11 14:39 UTC, mtbc commented on domains/manufacturing/guide.md
> +In our Chronicl domain specification this is captured as follows -
```suggestion
In our Chronicle domain specification this is captured as follows -
```

2022-11-11 14:41 UTC, mtbc commented on domains/manufacturing/guide.md
> +the `name` (in future release `external_id`) and `partId` were incremented.
Is it now `externalId` in even the present release?

2022-11-11 14:42 UTC, mtbc commented on domains/manufacturing/guide.md
> +Then we assert that it `wasGeneratedBy` by the relevant manufacturing activity.
Not convinced that the second "by" helps, but I don't strongly object.

2022-11-11 14:42 UTC, duncanjw commented on domains/manufacturing/guide.md
> +the `name` (in future release `external_id`) and `partId` were incremented.
Correct. Will fix

2022-11-11 14:44 UTC, duncanjw commented on domains/manufacturing/guide.md
> +Then we assert that it `wasGeneratedBy` by the relevant manufacturing activity.
Reads as was generated by without it :)

2022-11-11 14:46 UTC, mtbc commented
Also fixes needed to the other example domains but those could be in other PRs.

2022-11-11 14:47 UTC, duncanjw commented on domains/manufacturing/guide.md
> +In our Chronicl domain specification this is captured as follows -
Fixed

2022-11-11 14:49 UTC, mtbc commented on README.md
> +    txId
I'll leave it to @ryanbtp to think if we want to add `stage`.

2022-11-11 14:54 UTC, mtbc approved these changes
Looks good to me at least.

2022-11-17 15:55 UTC, duncanjw approved these changes

2022-11-17 15:56 UTC, merged

2022-11-17 15:57 UTC, scealiontach commented on README.md
> +    txId
deal with it at a later pull I think.  I don't see the semantics of those documented anywhere yet (maybe I missed it).  Best not to have "what is that?" items in the examples, until we can point to the answer.