feat: Run linter before compilation
blockchaintp/chronicle-examples pull request #23
Opened 2022-11-22 12:47 UTC by ryanbtp

* Fix the lower case role errors it found

Dependent on a .4 release of Chronicle

Signed-off-by: Ryan Roberts <ryan@blockchaintp.com>

2022-11-22 20:57 UTC, scealiontach commented
Hold this until 0.4.0 release

2022-11-22 20:57 UTC, scealiontach requested changes
hold until 0.4

2022-11-28 19:43 UTC, scealiontach requested changes

2022-11-28 19:43 UTC, scealiontach commented on domains/evidence/domain.yaml
> +  Versionies:
What's this? Looks like a typo

2022-11-28 19:46 UTC, suchapalaver commented on domains/evidence/domain.yaml
> +  Versionies:
Corrected.

2022-11-29 00:04 UTC, scealiontach approved these changes

2022-11-29 09:51 UTC, merged